# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UpstraSampleiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ImageSlideshow', '~> 1.9.0'
  pod "ImageSlideshow/Alamofire"
  pod 'lottie-ios'
  # pod 'UpstraUIKit', '1.8.1', :source => "https://github.com/EkoCommunications/EkoMessagingSDKUIKit.git"
  # Pods for UpstraSampleiOS
end
